server: Karion
global: '&2[G] &f{jobs} <prefix><group> <player><suffix>&2: <msg>'
hilfe: '&e[H] &f{jobs} <prefix><group> <player><suffix>&e: <msg>'
lokal: '&9[L] &f{jobs} <prefix><group> <player><suffix>&9: <msg>'
team: '&b[A] &f{jobs} <prefix><group> <player><suffix>&b: <msg>'
spy: '&7[&4Spy&7] [&4<server>&7] &f<prefix><group> <player><suffix>&7: <msg>'
pmspy: '&8[&4PmSpy&8] [&4<server>] &d<prefix><group> <from><suffix> &d-> <to>&d: <msg>'
srvpm: '&d<prefix><group> <from><suffix> &d-> <to>&d: <msg>'
to: '<prefix><group> <player><suffix>'
lokalchat: false 
radius: 100
name: '<player>'
debug: false
mysql:
  user: root
  password: password
  hostname: localhost
  database: skymine
  port: 3306
  praefix: skymine_