name: SimpleChat
main: com.github.calenria.simplechat.SimpleChat
version: 0.4.2
website: https://github.com/Calenria/SimpleChat
author: Calenria
description: SimpleChat!
database: false
depend: [Vault, WorldEdit]
softdepend: [Jobs]           
